name = "missiv-server"
main = "src/worker.ts"
compatibility_date = "2023-08-14"

compatibility_flags = [ "nodejs_compat" ] # for node:async_hooks

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "missiv-db"
database_id = "1c8f2d0f-7cef-47a0-bc2e-cdb63d5a266b"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "ServerObjectRoom" },
  { name = "LIMITERS", class_name = "ServerObjectRateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["ServerObjectRoom"]

[[migrations]]
tag = "v2"
new_classes = ["ServerObjectRateLimiter"]

#[[migrations]]
#tag = "v1"
#new_classes = ["ServerObjectRoom", "ServerObjectRateLimiter"]
